### ISSUE TITLE
Grid Demo

### ISSUE THREAD

**Issue by greenyouse** [kitsonk/hokan#3]
Is there any way to load an IDB object store and display it in an OnDemandGrid with dgrid?  Sorry if this was an easy question but I can't quite get it to work.

Thanks!

**Comment by kitsonk** [comment]
It is likely you aren't waiting for the IndexedDB to be ready before initialising the grid.  This has to do with the async nature of IndexedDB and the situation that dgrid appears to introspect the IndexedDB for feature testing before it actually startups up, which causes errors.  I will need to make this clearer in the documentation.  You need to do something like this:

``` js
require(['dgrid/OnDemandGrid', 'hokan/IndexedDB', 'dojo/when',
function(OnDemandGrid, IndexedDB, when) {
  var idb = new IndexedDB();
  when(idb.ready).then(function () {
    var grid = new OnDemandGrid({
      store: idb
    }, 'grid');
    grid.startup();
  });
});
```

Here is a gist that I have that works: https://gist.github.com/kitsonk/5254923

**Comment by greenyouse** [comment]
Like you said, I missed waiting for IndexedDB before loading the grid.  Thank you for the examples, these made it much easier to see how to build a grid.
